project:
  type: website
  output-dir: _site
  resources:
    - assets/**
    - Julia/Lectures/**

website:
  title: "Xing Xu"
  site-url: https://xingxu-econ.github.io/
  description: "Xing Xu — Economics, University of Minnesota. International Macro."
  favicon: assets/University_of_Minnesota.svg
  open-graph: true
  twitter-card:
    card-style: summary
    creator: "@VincentXingXu"
  repo-url: https://github.com/2xu2
  repo-actions: [issue]
  bread-crumbs: true

  navbar:
    pinned: true
    left:
      - text: Homepage
        href: index.qmd
        icon: house
      - text: Research
        href: research.qmd
        icon: journal-text
      - text: CV
        href: cv.qmd
        icon: file-earmark-person
      - text: Teaching
        href: teaching.qmd
        icon: mortarboard
      - text: Julia Lectures
        icon: code-slash
        menu:
          - text: "Fundamentals"
            href: Julia/Lectures/Julia_Lec_1_Compecon_Xing_Xu.ipynb
          - text: "Neo-classical Growth"
            href: Julia/Lectures/Julia_Lec_2_Compecon_Xing_Xu.ipynb
          - text: "Solvers and Interpolation"
            href: Julia/Lectures/Julia_Lec_3_Compecon_Xing_Xu.ipynb
          - text: "Incomplete Markets"
            href: Julia/Lectures/Julia_Lec_4_Compecon_Xing_Xu.ipynb
          - text: "Firm Dynamics"
            href: Julia/Lectures/Julia_Lec_5_Compecon_Xing_Xu.ipynb
          - text: "Job Search"
            href: Julia/Lectures/Julia_Lec_6_Compecon_Xing_Xu.ipynb
    right:
      - text: "Email"
        icon: envelope-fill
        href: xu000956@umn.edu
      - icon: github
        aria-label: GitHub
        href: https://github.com/2xu2

  page-footer:
    left: "© 2025 Xing Xu · University of Minnesota · [xu000956@umn.edu](xu000956@umn.edu)"

  # Search is enabled by default; configure it here
  search:
    location: navbar
    type: overlay
    limit: 20
    collapse-after: 2

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 3
    smooth-scroll: true
    link-external-newwindow: true
    code-copy: true
    code-overflow: wrap
    df-print: paged
    highlight-style: github

execute:
  freeze: auto
  echo: true
  warning: false
  message: false
  cache: true

